// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// climateDF2arrayCpp
NumericVector climateDF2arrayCpp(NumericMatrix climate_dt, IntegerVector site_ids, IntegerVector year_ids, bool include_month, bool include_day, int Nsites, int Nyears, int Nmonths, int Ndays, int Nenv, CharacterVector env_vars);
RcppExport SEXP _FINN_climateDF2arrayCpp(SEXP climate_dtSEXP, SEXP site_idsSEXP, SEXP year_idsSEXP, SEXP include_monthSEXP, SEXP include_daySEXP, SEXP NsitesSEXP, SEXP NyearsSEXP, SEXP NmonthsSEXP, SEXP NdaysSEXP, SEXP NenvSEXP, SEXP env_varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type climate_dt(climate_dtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type site_ids(site_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type year_ids(year_idsSEXP);
    Rcpp::traits::input_parameter< bool >::type include_month(include_monthSEXP);
    Rcpp::traits::input_parameter< bool >::type include_day(include_daySEXP);
    Rcpp::traits::input_parameter< int >::type Nsites(NsitesSEXP);
    Rcpp::traits::input_parameter< int >::type Nyears(NyearsSEXP);
    Rcpp::traits::input_parameter< int >::type Nmonths(NmonthsSEXP);
    Rcpp::traits::input_parameter< int >::type Ndays(NdaysSEXP);
    Rcpp::traits::input_parameter< int >::type Nenv(NenvSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type env_vars(env_varsSEXP);
    rcpp_result_gen = Rcpp::wrap(climateDF2arrayCpp(climate_dt, site_ids, year_ids, include_month, include_day, Nsites, Nyears, Nmonths, Ndays, Nenv, env_vars));
    return rcpp_result_gen;
END_RCPP
}
// obsDF2arraysCpp
List obsDF2arraysCpp(DataFrame obs_dt, CharacterVector extra_cols);
RcppExport SEXP _FINN_obsDF2arraysCpp(SEXP obs_dtSEXP, SEXP extra_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type obs_dt(obs_dtSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type extra_cols(extra_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(obsDF2arraysCpp(obs_dt, extra_cols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FINN_climateDF2arrayCpp", (DL_FUNC) &_FINN_climateDF2arrayCpp, 11},
    {"_FINN_obsDF2arraysCpp", (DL_FUNC) &_FINN_obsDF2arraysCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_FINN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
