# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

climateDF2arrayCpp <- function(climate_dt, site_ids, year_ids, include_month, Nsites, Nyears, Nmonths, Nenv) {
    .Call(`_FINN_climateDF2arrayCpp`, climate_dt, site_ids, year_ids, include_month, Nsites, Nyears, Nmonths, Nenv)
}

obsDF2arraysCpp <- function(obs_dt) {
    .Call(`_FINN_obsDF2arraysCpp`, obs_dt)
}

